// Studio publish: encrypt a game build with its edition's content key and
// pin it to IPFS. Prints the CID + hash to record on-chain.
//
//   PINATA_JWT=<jwt> npm run publish -w station -- <game> <editionId>
//   ex:  npm run publish -w station -- snake 3
//
// Legacy note: edition 2 (runner) keeps the original dev content key; the
// runner build.enc is regenerated by make-dev-ticket, not by this script.

import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { putBuild } from "@gamevault/shared/storage";
import { encryptBuild } from "@gamevault/shared";
import { devContentKeyFor } from "@gamevault/shared/devkeys";

const [game, editionId] = process.argv.slice(2);
if (!game || !editionId) {
  console.error("Usage: npm run publish -w station -- <game> <editionId>   ex: snake 3");
  process.exit(1);
}

const jwt = process.env.PINATA_JWT;
if (!jwt) {
  console.error("❌ PINATA_JWT manquant (https://app.pinata.cloud → API Keys)");
  process.exit(1);
}

const bundle = join(dirname(fileURLToPath(import.meta.url)), `../../game/dist/${game}.html`);
if (!existsSync(bundle)) {
  console.error(`❌ ${bundle} introuvable — npm run build -w game`);
  process.exit(1);
}

const plain = new Uint8Array(readFileSync(bundle));
const enc = encryptBuild(plain, devContentKeyFor(editionId));
console.log(`Chiffrement (clé édition ${editionId}) + pin de ${game} (${(enc.length / 1024 / 1024).toFixed(2)} Mo)…`);

const stored = await putBuild(enc, `gamevault-${game}-ed${editionId}-build.enc`, jwt);

console.log(`\n✔ Épinglé.`);
console.log(`  CID    : ${stored.cid}`);
console.log(`  sha256 : ${stored.sha256}`);
console.log(`\nÀ enregistrer :`);
console.log(`  - shared/src/catalog.ts (buildCid/buildSha256 de l'édition ${editionId})`);
console.log(`  - on-chain : GameRegistry.createEdition(..., "${stored.cid}", ${stored.sha256})`);
