// EIP-4361-shaped pairing message. Built by web/ (signing page), verified by
// ticketd. Single source of truth for the format — signer and verifier MUST
// use this module, never hand-build the string.
//
// The device pubkey is EMBEDDED in the message: the owner's signature covers
// exactly which device gets authorized (no device substitution).
//
// Self-contained module (no internal imports) so bundlers can import it as
// a subpath: `@gamevault/shared/siwe`.

export interface PairingParams {
  /** Wallet address that will sign (the license owner) */
  address: string;
  chainId: number;
  /** Compressed secp256k1 pubkey of the launcher device (0x-hex) */
  devicePubKey: string;
  /** Random nonce generated by the launcher for this pairing */
  nonce: string;
  tokenId: string;
  contract: string;
  /** ISO timestamp */
  issuedAt: string;
  domain?: string;
}

export function buildPairingMessage(p: PairingParams): string {
  const domain = p.domain ?? "gamevault.local";
  return [
    `${domain} wants you to sign in with your Ethereum account:`,
    p.address,
    ``,
    `Authorize device ${p.devicePubKey} to decrypt GameVault licenses owned by this wallet.`,
    ``,
    `URI: https://${domain}/pair`,
    `Version: 1`,
    `Chain ID: ${p.chainId}`,
    `Nonce: ${p.nonce}`,
    `Issued At: ${p.issuedAt}`,
    `Resources:`,
    `- gamevault:device:${p.devicePubKey}`,
    `- gamevault:license:${p.contract}/${p.tokenId}`,
  ].join("\n");
}
